apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: predictops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rabelmervin/PredictOps.git
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  info:
    - name: 'Documentation'
      value: 'https://github.com/rabelmervin/PredictOps'
